/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Dhitiwat
 */
public class FoodDisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodDisplayPanel
     */
    public static final int WIDTH = 350;
    public static final int HEIGHT = 425;
    Food food;
    int selectedLanguage;

    public FoodDisplayPanel() {
        initComponents();
    }

    public FoodDisplayPanel(Color c) {
        initComponents();
        this.setBackground(c);
    }

    public FoodDisplayPanel(Food f, int select) {
        initComponents();
        this.food = f;
        this.selectedLanguage = select;
        this.setImage();
        this.setName();
        this.setPrice();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodIconLabel = new javax.swing.JLabel();
        foodNameLabel = new javax.swing.JLabel();
        foodPriceLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(350, 425));
        setMinimumSize(new java.awt.Dimension(350, 425));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(350, 425));

        foodIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodIconLabel.setPreferredSize(new java.awt.Dimension(326, 242));

        foodNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        foodNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodNameLabel.setText("12345678901234567890");
        foodNameLabel.setPreferredSize(new java.awt.Dimension(326, 66));

        foodPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        foodPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodPriceLabel.setText("jLabel1");
        foodPriceLabel.setPreferredSize(new java.awt.Dimension(326, 66));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foodNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(foodIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foodNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foodPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setImage() {
        this.foodIconLabel.setIcon(this.food.getImage());
    }

    private void setName() {
        String name = this.food.getName(selectedLanguage);
        if (name.length() > 20) {
            String temp = "<html><div align=\"center\">";
            int countSpace = 0;
            for (int i = 0; i < name.length(); ++i) {
                if (name.charAt(i) == ' ') {
                    ++countSpace;
                    if (countSpace == 3) {
                        temp += "<br>";
                    }
                }
                temp += name.charAt(i);
            }
            temp += "</div></html>";
            name = new String(temp);
        }
        this.foodNameLabel.setText(name);
    }

    private void setPrice() {
        this.foodPriceLabel.setText("฿ " + String.format("%.2f", this.food.getPrice()));
    }

    public void setBorder(boolean set) {
        if (set) {
            this.setBackground(new Color(116, 197, 229));
            foodNameLabel.setFont(new Font("Tahoma",Font.BOLD,24));
            foodPriceLabel.setFont(new Font("Tahoma",Font.BOLD,18));
        } else {
            this.setBackground(new Color(255,255,255));
            foodNameLabel.setFont(new Font("Tahoma",Font.PLAIN,24));
            foodPriceLabel.setFont(new Font("Tahoma",Font.PLAIN,18));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foodIconLabel;
    private javax.swing.JLabel foodNameLabel;
    private javax.swing.JLabel foodPriceLabel;
    // End of variables declaration//GEN-END:variables

}
