/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.Point;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Dhitiwat
 */
public class TableGui extends javax.swing.JFrame {

    /**
     * Creates new form TableGui
     */
    public static int TABLE_NUMBER = 1;
    public static final String DATABASE_HOST_IP = "192.168.1.45";
    public static final String DATABASE_USERNAME = "charn";
    public static final String DATABASE_PASSWORD = "123456";
    public static final String SOCKET_HOST_IP = "127.0.0.1";

    public Table thisTable;
    public int selectedLanguage; // 0 English /  1 Thai
    public int totalOrder;
    public int totalOrderSelection;

    private String[] addButtonText = {"ADD", "เพิ่ม"};
    private String[] backButtonText = {"BACK", "กลับ"};
    private String[] callStaffButtonText = {"Call Staff", "เรียกพนักงาน"};
    private String[] welcomeText = {"Welcome", "ยินดีต้อนรับ"};
    private String[] orderButtonText = {"ORDER", "รายการที่สั่ง"};
    private String[] orderedLabelText = {"Ordered", "สั่งไปแล้ว"};
    private String[] topNumberLabelText = {"Table Of: ", "จำนวนบุคคล: "};
    private String[] removeButtonText = {"Remove", "ลบ"};
    private String[] sendOrderButtonText = {"Send Order", "ส่งรายการ"};
    private String[] viewBillButtonText = {"View Bill", "ตรวจสอบรายการ"};
    private String[] menuButtonText = {"Back To Menu", "กลับสู่รายการ"};
    private String[] checkBillButtonText = {"Check Bill", "ชำระค่าอาหาร"};
    private String[] infoTotalMenuText = {"Total Menu Order :", "จำนวนรายการที่สั่ง"};
    private String[] infoTotalPriceText = {"Total Price :", "ยอดรายการทั้งหมด"};
    private String[] infoPriceEachText = {"Price For Each Person : ", "ราคาต่อบุคคล"};

    public Map<Food, Integer> selectedFood;
    public Map<Food, Integer> selectedDrinks;
    public int removingSelection;
    public SocketClient client;
    Date dateObj;
    DateFormat dateFormat;

    Database db;
    ArrayList<String> foodCategoryEnglish;
    ArrayList<String> foodCategoryThai;
    ArrayList<Food> foodAccordingToCetagory;
    int selectedMenuIndex;
    ArrayList<FoodDisplayPanel> foodAccordingToCetagoryIcon;

    public TableGui() {
        initComponents();
        selectedLanguage = 0;
        cartPanel.setVisible(false);
        menuPanel.setVisible(false);
        billPanel.setVisible(false);

        selectedFood = new HashMap<>();
        selectedDrinks = new HashMap<>();
        thisTable = new Table(TABLE_NUMBER);
        removingSelection = -1;
        totalOrder = 0;
        totalOrderSelection = 0;

        db = new Database(DATABASE_HOST_IP, DATABASE_USERNAME, DATABASE_PASSWORD);
        foodCategoryEnglish = db.getEnglishCategory();
        foodCategoryThai = db.getThaiCategory();
        foodAccordingToCetagoryIcon = new ArrayList<>();

        this.buttonConfig();
        this.setTextAccrodingToSelectedLanguage();
    

    }

    public void setupConnectionWithHost() {
        client = new SocketClient(SOCKET_HOST_IP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        toEnglish = new javax.swing.JLabel();
        callStaffButton = new javax.swing.JButton();
        toThai = new javax.swing.JLabel();
        topNumberLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        startPanel = new javax.swing.JPanel();
        startButtonLabel = new javax.swing.JPanel();
        startButton1 = new javax.swing.JButton();
        startButton2 = new javax.swing.JButton();
        startButton3 = new javax.swing.JButton();
        startButton4 = new javax.swing.JButton();
        startButton5 = new javax.swing.JButton();
        startButton6 = new javax.swing.JButton();
        startButton7 = new javax.swing.JButton();
        startButton8 = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        orderedLabel = new javax.swing.JLabel();
        numOrderedLabel = new javax.swing.JLabel();
        numberOfOrderedSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodCategoryList = new javax.swing.JList<>();
        priceLabel = new javax.swing.JLabel();
        bahtLabel = new javax.swing.JLabel();
        menuDisplayScrollPane = new javax.swing.JScrollPane();
        menuDisplayPanel = new javax.swing.JPanel();
        cartPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        selectedDisplayScrollPane = new javax.swing.JScrollPane();
        selectedPanel = new javax.swing.JPanel();
        orderdLabel = new javax.swing.JLabel();
        foodList = new javax.swing.JList<>();
        drinksList = new javax.swing.JList<>();
        removeButton = new javax.swing.JButton();
        sendOrderButton = new javax.swing.JButton();
        viewBillButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        billPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billInfoPanel = new javax.swing.JPanel();
        billTableLabel = new javax.swing.JLabel();
        billTableNumberLabel = new javax.swing.JLabel();
        billPeopleLabel = new javax.swing.JLabel();
        billNumberOfPeopleLabel = new javax.swing.JLabel();
        billBarLabel = new javax.swing.JLabel();
        billQtyLabel = new javax.swing.JLabel();
        billTimeLabel = new javax.swing.JLabel();
        billDescriptionLabel = new javax.swing.JLabel();
        billPriceLabel = new javax.swing.JLabel();
        billFoodQtyLabel = new javax.swing.JLabel();
        billFoodDescriptionLabel = new javax.swing.JLabel();
        billFoodPriceLabel = new javax.swing.JLabel();
        billBarLabel2 = new javax.swing.JLabel();
        billDrinksQtyLabel = new javax.swing.JLabel();
        billDrinksDescriptionLabel = new javax.swing.JLabel();
        billDrinksPriceLabel = new javax.swing.JLabel();
        extraCostLabel = new javax.swing.JPanel();
        serviceChargeCostLabel = new javax.swing.JLabel();
        totalCostLabel = new javax.swing.JLabel();
        sericeChargeLabel = new javax.swing.JLabel();
        vatLabel = new javax.swing.JLabel();
        vatCostLabel = new javax.swing.JLabel();
        billDiscountLabel = new javax.swing.JLabel();
        billDiscountCostLabel = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        infoTotalMenu = new javax.swing.JLabel();
        infoTotalPrice = new javax.swing.JLabel();
        infoPriceEach = new javax.swing.JLabel();
        infoTotalMenuNumber = new javax.swing.JLabel();
        infoTotalPriceNumber = new javax.swing.JLabel();
        infoPriceEachNumber = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        checkBillButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        topPanel.setBackground(new java.awt.Color(85, 194, 237));
        topPanel.setForeground(new java.awt.Color(85, 194, 237));
        topPanel.setToolTipText("");
        topPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        topPanel.setName(""); // NOI18N
        topPanel.setPreferredSize(new java.awt.Dimension(1280, 120));

        toEnglish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/englishFlag.jpg"))); // NOI18N
        toEnglish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toEnglishMouseClicked(evt);
            }
        });

        callStaffButton.setBackground(new java.awt.Color(244, 133, 142));
        callStaffButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        callStaffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/b_call_black.png"))); // NOI18N
        callStaffButton.setText("Call Staff");
        callStaffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                callStaffButtonMouseClicked(evt);
            }
        });

        toThai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/thaiFlag.jpg"))); // NOI18N
        toThai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toThaiMouseClicked(evt);
            }
        });

        topNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        topNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        topNumberLabel.setText(" ");
        topNumberLabel.setAlignmentY(0.0F);

        logoLabel.setBackground(new java.awt.Color(85, 194, 237));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/logo_fahsai.png"))); // NOI18N

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(logoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(topNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(callStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(toThai)
                .addGap(31, 31, 31)
                .addComponent(toEnglish)
                .addGap(28, 28, 28))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoLabel)
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(callStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(topNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(toEnglish)
                    .addComponent(toThai))
                .addGap(52, 52, 52))
        );

        startPanel.setBackground(new java.awt.Color(255, 255, 255));
        startPanel.setForeground(new java.awt.Color(191, 159, 101));
        startPanel.setFont(new java.awt.Font("DilleniaUPC", 3, 13)); // NOI18N
        startPanel.setPreferredSize(new java.awt.Dimension(1280, 580));

        startButtonLabel.setBackground(new java.awt.Color(255, 255, 255));
        startButtonLabel.setLayout(new java.awt.GridLayout(2, 0, 40, 25));

        startButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/person1.png"))); // NOI18N
        startButton1.setDefaultCapable(false);
        startButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButton1MouseClicked(evt);
            }
        });
        startButtonLabel.add(startButton1);

        startButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/person2.png"))); // NOI18N
        startButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButton2MouseClicked(evt);
            }
        });
        startButtonLabel.add(startButton2);

        startButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/person3.png"))); // NOI18N
        startButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButton3MouseClicked(evt);
            }
        });
        startButtonLabel.add(startButton3);

        startButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/person4.png"))); // NOI18N
        startButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButton4MouseClicked(evt);
            }
        });
        startButtonLabel.add(startButton4);

        startButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/person5.png"))); // NOI18N
        startButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButton5MouseClicked(evt);
            }
        });
        startButtonLabel.add(startButton5);

        startButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/person6.png"))); // NOI18N
        startButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButton6MouseClicked(evt);
            }
        });
        startButtonLabel.add(startButton6);

        startButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/person7.png"))); // NOI18N
        startButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButton7MouseClicked(evt);
            }
        });
        startButtonLabel.add(startButton7);

        startButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/person8.png"))); // NOI18N
        startButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButton8MouseClicked(evt);
            }
        });
        startButtonLabel.add(startButton8);

        welcomeLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 72)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(166, 218, 239));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(startButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addComponent(welcomeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(welcomeLabel)
                .addGap(54, 54, 54)
                .addComponent(startButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setForeground(new java.awt.Color(215, 177, 101));
        menuPanel.setAlignmentX(0.0F);
        menuPanel.setAlignmentY(0.0F);
        menuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPanel.setPreferredSize(new java.awt.Dimension(1280, 570));

        addButton.setBackground(new java.awt.Color(19, 187, 106));
        addButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/b_add.png"))); // NOI18N
        addButton.setText("ADD");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        orderButton.setBackground(new java.awt.Color(40, 180, 125));
        orderButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderButton.setForeground(new java.awt.Color(255, 255, 255));
        orderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/b_cart.png"))); // NOI18N
        orderButton.setText("ORDER ( 0 )");
        orderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderButtonMouseClicked(evt);
            }
        });

        orderedLabel.setBackground(new java.awt.Color(0, 0, 0));
        orderedLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        orderedLabel.setForeground(new java.awt.Color(85, 194, 237));
        orderedLabel.setText("Ordered");

        numOrderedLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numOrderedLabel.setForeground(new java.awt.Color(85, 194, 237));
        numOrderedLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numOrderedLabel.setText("0");

        numberOfOrderedSpinner.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numberOfOrderedSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        numberOfOrderedSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numberOfOrderedSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numberOfOrderedSpinnerStateChanged(evt);
            }
        });

        foodCategoryList.setBackground(javax.swing.UIManager.getDefaults().getColor("TextField.light"));
        foodCategoryList.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        foodCategoryList.setModel(new DefaultListModel());
        foodCategoryList.setSelectedIndex(0);
        foodCategoryList.setSelectionBackground(new java.awt.Color(135, 200, 229));
        foodCategoryList.setSelectionForeground(new java.awt.Color(255, 255, 251));
        foodCategoryList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodCategoryListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(foodCategoryList);

        priceLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(85, 194, 237));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priceLabel.setText("0");

        bahtLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bahtLabel.setForeground(new java.awt.Color(85, 194, 237));
        bahtLabel.setText("฿");

        menuDisplayScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        menuDisplayPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDisplayPanelMouseClicked(evt);
            }
        });
        menuDisplayPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        menuDisplayScrollPane.setViewportView(menuDisplayPanel);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(orderedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numOrderedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(orderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuDisplayScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(bahtLabel)
                        .addGap(18, 18, 18)
                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(numberOfOrderedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menuDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberOfOrderedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bahtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numOrderedLabel)
                            .addComponent(orderedLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        cartPanel.setBackground(new java.awt.Color(255, 255, 255));
        cartPanel.setAlignmentX(0.0F);
        cartPanel.setAlignmentY(0.0F);
        cartPanel.setPreferredSize(new java.awt.Dimension(1280, 570));

        backButton.setBackground(new java.awt.Color(255, 51, 51));
        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/b_back.png"))); // NOI18N
        backButton.setText("BACK");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        selectedDisplayScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        orderdLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderdLabel.setText("Ordered ");

        foodList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        foodList.setModel(new DefaultListModel());
        foodList.setSelectionBackground(new java.awt.Color(255, 255, 255));
        foodList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodListMouseClicked(evt);
            }
        });

        drinksList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drinksList.setModel(new DefaultListModel());
        drinksList.setSelectionBackground(new java.awt.Color(255, 255, 255));
        drinksList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinksListMouseClicked(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(255, 51, 51));
        removeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/b_bin.png"))); // NOI18N
        removeButton.setText("Remove");
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout selectedPanelLayout = new javax.swing.GroupLayout(selectedPanel);
        selectedPanel.setLayout(selectedPanelLayout);
        selectedPanelLayout.setHorizontalGroup(
            selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(foodList, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addComponent(drinksList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        selectedPanelLayout.setVerticalGroup(
            selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectedPanelLayout.createSequentialGroup()
                        .addComponent(foodList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(selectedPanelLayout.createSequentialGroup()
                        .addComponent(orderdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 239, Short.MAX_VALUE)))
                .addGroup(selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(drinksList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        selectedDisplayScrollPane.setViewportView(selectedPanel);

        sendOrderButton.setBackground(new java.awt.Color(19, 187, 106));
        sendOrderButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sendOrderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/b_chef.png"))); // NOI18N
        sendOrderButton.setText("Send Order");
        sendOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendOrderButtonMouseClicked(evt);
            }
        });

        viewBillButton.setBackground(new java.awt.Color(85, 194, 237));
        viewBillButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewBillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/b_paper.png"))); // NOI18N
        viewBillButton.setText("View Bill");
        viewBillButton.setPreferredSize(new java.awt.Dimension(121, 31));
        viewBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBillButtonMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/ads.gif"))); // NOI18N

        javax.swing.GroupLayout cartPanelLayout = new javax.swing.GroupLayout(cartPanel);
        cartPanel.setLayout(cartPanelLayout);
        cartPanelLayout.setHorizontalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartPanelLayout.createSequentialGroup()
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cartPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sendOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cartPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addGroup(cartPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(selectedDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        cartPanelLayout.setVerticalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(cartPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectedDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cartPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewBillButton, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(sendOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        billPanel.setBackground(new java.awt.Color(255, 255, 255));
        billPanel.setAlignmentX(0.0F);
        billPanel.setAlignmentY(0.0F);
        billPanel.setPreferredSize(new java.awt.Dimension(1280, 570));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        billInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        billTableLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        billTableLabel.setForeground(new java.awt.Color(192, 194, 193));
        billTableLabel.setText("Table :");

        billTableNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        billTableNumberLabel.setForeground(new java.awt.Color(72, 178, 218));
        billTableNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billTableNumberLabel.setText("00");

        billPeopleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billPeopleLabel.setForeground(new java.awt.Color(159, 173, 176));
        billPeopleLabel.setText("Number of People:");

        billNumberOfPeopleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billNumberOfPeopleLabel.setForeground(new java.awt.Color(72, 178, 218));
        billNumberOfPeopleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billNumberOfPeopleLabel.setText("00");

        billBarLabel.setFont(new java.awt.Font("MingLiU-ExtB", 1, 18)); // NOI18N
        billBarLabel.setForeground(new java.awt.Color(127, 131, 132));
        billBarLabel.setText("==========================================================");

        billQtyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billQtyLabel.setForeground(new java.awt.Color(180, 184, 183));
        billQtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billQtyLabel.setText("Qty");

        billTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billTimeLabel.setForeground(new java.awt.Color(72, 178, 218));
        billTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billTimeLabel.setText("00:00:00");

        billDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billDescriptionLabel.setForeground(new java.awt.Color(180, 184, 183));
        billDescriptionLabel.setText("Description");

        billPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billPriceLabel.setForeground(new java.awt.Color(180, 184, 183));
        billPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        billPriceLabel.setText("Price");

        billFoodQtyLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        billFoodQtyLabel.setForeground(new java.awt.Color(180, 184, 183));
        billFoodQtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billFoodQtyLabel.setText("0");

        billFoodDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        billFoodDescriptionLabel.setForeground(new java.awt.Color(180, 184, 183));
        billFoodDescriptionLabel.setText("Tom Yum Kung");

        billFoodPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        billFoodPriceLabel.setForeground(new java.awt.Color(180, 184, 183));
        billFoodPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        billFoodPriceLabel.setText("00.00");

        billBarLabel2.setFont(new java.awt.Font("Felix Titling", 0, 13)); // NOI18N
        billBarLabel2.setText("==============================================================================");

        billDrinksQtyLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        billDrinksQtyLabel.setForeground(new java.awt.Color(180, 184, 183));
        billDrinksQtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billDrinksQtyLabel.setText("0");

        billDrinksDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        billDrinksDescriptionLabel.setForeground(new java.awt.Color(180, 184, 183));
        billDrinksDescriptionLabel.setText("Coca Cola");

        billDrinksPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        billDrinksPriceLabel.setForeground(new java.awt.Color(180, 184, 183));
        billDrinksPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        billDrinksPriceLabel.setText("00.00");

        extraCostLabel.setBackground(new java.awt.Color(255, 255, 255));

        serviceChargeCostLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        serviceChargeCostLabel.setForeground(new java.awt.Color(180, 184, 183));
        serviceChargeCostLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        serviceChargeCostLabel.setText("0.00");

        totalCostLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalCostLabel.setForeground(new java.awt.Color(34, 183, 216));
        totalCostLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalCostLabel.setText("0");

        sericeChargeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sericeChargeLabel.setForeground(new java.awt.Color(180, 184, 183));
        sericeChargeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sericeChargeLabel.setText("Service Charge");

        vatLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        vatLabel.setForeground(new java.awt.Color(180, 184, 183));
        vatLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vatLabel.setText("VAT");

        vatCostLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        vatCostLabel.setForeground(new java.awt.Color(180, 184, 183));
        vatCostLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vatCostLabel.setText("0.00");

        billDiscountLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        billDiscountLabel.setForeground(new java.awt.Color(180, 184, 183));
        billDiscountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        billDiscountLabel.setText("Bill Discount");

        billDiscountCostLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        billDiscountCostLabel.setForeground(new java.awt.Color(180, 184, 183));
        billDiscountCostLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        billDiscountCostLabel.setText("0.00");

        javax.swing.GroupLayout extraCostLabelLayout = new javax.swing.GroupLayout(extraCostLabel);
        extraCostLabel.setLayout(extraCostLabelLayout);
        extraCostLabelLayout.setHorizontalGroup(
            extraCostLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extraCostLabelLayout.createSequentialGroup()
                .addGroup(extraCostLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(extraCostLabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(totalCostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extraCostLabelLayout.createSequentialGroup()
                        .addGroup(extraCostLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sericeChargeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(vatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(billDiscountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(extraCostLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vatCostLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(billDiscountCostLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(serviceChargeCostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        extraCostLabelLayout.setVerticalGroup(
            extraCostLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extraCostLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(extraCostLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billDiscountLabel)
                    .addComponent(billDiscountCostLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(extraCostLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vatCostLabel)
                    .addComponent(vatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(extraCostLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serviceChargeCostLabel)
                    .addComponent(sericeChargeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout billInfoPanelLayout = new javax.swing.GroupLayout(billInfoPanel);
        billInfoPanel.setLayout(billInfoPanelLayout);
        billInfoPanelLayout.setHorizontalGroup(
            billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billInfoPanelLayout.createSequentialGroup()
                .addGroup(billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(billBarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(billInfoPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(billTableLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billTableNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(billPeopleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billNumberOfPeopleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(billTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(billBarLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billInfoPanelLayout.createSequentialGroup()
                .addGroup(billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(billInfoPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(extraCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(billInfoPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(billQtyLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(billDrinksQtyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(billFoodQtyLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(billInfoPanelLayout.createSequentialGroup()
                                .addComponent(billDrinksDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(billDrinksPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(billInfoPanelLayout.createSequentialGroup()
                                .addGroup(billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(billDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(billFoodDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(billPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(billFoodPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        billInfoPanelLayout.setVerticalGroup(
            billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billTableNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(billPeopleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billNumberOfPeopleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billBarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billDescriptionLabel)
                    .addComponent(billPriceLabel)
                    .addComponent(billQtyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billFoodDescriptionLabel)
                    .addComponent(billFoodPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(billFoodQtyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(billBarLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billDrinksPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(billDrinksDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(billDrinksQtyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(extraCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(billInfoPanel);

        infoTotalMenu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        infoTotalMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoTotalMenu.setText("Total Menu Order :");

        infoTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        infoTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoTotalPrice.setText("Total Price :");

        infoPriceEach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        infoPriceEach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoPriceEach.setText("Price for Each Person :");

        infoTotalMenuNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        infoTotalMenuNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoTotalMenuNumber.setText("0");

        infoTotalPriceNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        infoTotalPriceNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoTotalPriceNumber.setText("0");

        infoPriceEachNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        infoPriceEachNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoPriceEachNumber.setText("0");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoTotalMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoPriceEach, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(infoPriceEachNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(infoTotalMenuNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infoTotalPriceNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                .addGap(54, 54, 54))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoTotalMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoTotalMenuNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoTotalPriceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoPriceEach, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoPriceEachNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        menuButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/b_spoon.png"))); // NOI18N
        menuButton.setText("Back To Menu");
        menuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButtonMouseClicked(evt);
            }
        });

        checkBillButton.setBackground(new java.awt.Color(129, 162, 198));
        checkBillButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkBillButton.setForeground(new java.awt.Color(99, 99, 99));
        checkBillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/pic/b_coins.png"))); // NOI18N
        checkBillButton.setText("Check Bill");
        checkBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBillButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout billPanelLayout = new javax.swing.GroupLayout(billPanel);
        billPanel.setLayout(billPanelLayout);
        billPanelLayout.setHorizontalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(checkBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        billPanelLayout.setVerticalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billPanelLayout.createSequentialGroup()
                        .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(billPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(billPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderButtonMouseClicked
        // TODO add your handling code here:
        menuPanel.setVisible(false);
        cartPanel.setVisible(true);
        billPanel.setVisible(false);

        updateSelectedMenu();
    }//GEN-LAST:event_orderButtonMouseClicked

    private void foodCategoryListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodCategoryListMouseClicked
        // TODO add your handling code here:
        int ndx = foodCategoryList.getSelectedIndex();
        System.out.println(foodCategoryList.getSelectedValue());
        String chosenCategory = foodCategoryList.getSelectedValue();
        foodAccordingToCetagory = db.getFoodByCategory(chosenCategory, selectedLanguage);
        addFoodToDisplay();
        selectedMenuIndex = 0;

    }//GEN-LAST:event_foodCategoryListMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:]
        cartPanel.setVisible(false);
        menuPanel.setVisible(true);
        billPanel.setVisible(false);
        setTextAccrodingToSelectedLanguage();
    }//GEN-LAST:event_backButtonMouseClicked

    private void startButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButton1MouseClicked
        try {
            // TODO add your handling code here:
            setUpTable(1);
        } catch (IOException ex) {
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startButton1MouseClicked

    private void startButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButton2MouseClicked
        try {
            // TODO add your handling code here:
            setUpTable(2);
        } catch (IOException ex) {
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startButton2MouseClicked

    private void startButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButton3MouseClicked
        try {
            // TODO add your handling code here:
            setUpTable(3);
        } catch (IOException ex) {
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startButton3MouseClicked

    private void startButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButton4MouseClicked
        try {
            // TODO add your handling code here:
            setUpTable(4);
        } catch (IOException ex) {
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startButton4MouseClicked

    private void startButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButton5MouseClicked
        try {
            // TODO add your handling code here:
            setUpTable(5);
        } catch (IOException ex) {
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startButton5MouseClicked

    private void startButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButton6MouseClicked
        try {
            // TODO add your handling code here:
            setUpTable(6);
        } catch (IOException ex) {
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startButton6MouseClicked

    private void startButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButton7MouseClicked
        try {
            // TODO add your handling code here:
            setUpTable(7);
        } catch (IOException ex) {
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startButton7MouseClicked

    private void startButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButton8MouseClicked
        try {
            // TODO add your handling code here:
            setUpTable(8);
        } catch (IOException ex) {
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startButton8MouseClicked

    private void toEnglishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toEnglishMouseClicked
        // TODO add your handling code here:
        if (selectedLanguage != 0) {
            selectedLanguage = 0;
            setTextAccrodingToSelectedLanguage();
        }
    }//GEN-LAST:event_toEnglishMouseClicked

    private void toThaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toThaiMouseClicked
        // TODO add your handling code here:
        if (selectedLanguage != 1) {
            selectedLanguage = 1;
            setTextAccrodingToSelectedLanguage();
        }
    }//GEN-LAST:event_toThaiMouseClicked

    private void callStaffButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callStaffButtonMouseClicked
        System.out.println("Calling Waiter");
        try {
            // TODO add your handling code here:
            client.send(new Message("call waiter", thisTable.id));
        } catch (IOException ex) {
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_callStaffButtonMouseClicked

    private void foodListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodListMouseClicked
        // TODO add your handling code here:
        removingSelection = 0;
        int ndx = foodList.getSelectedIndex();
        drinksList.setSelectedIndex(-1);
        System.out.println(foodList.getSelectedValue());
    }//GEN-LAST:event_foodListMouseClicked

    private void drinksListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinksListMouseClicked
        // TODO add your handling code here:
        removingSelection = 1;
        int ndx = drinksList.getSelectedIndex();
        foodList.setSelectedIndex(-1);
        System.out.println(drinksList.getSelectedValue());

    }//GEN-LAST:event_drinksListMouseClicked

    private void removeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseClicked
        // TODO add your handling code here:
        int foodNdx = foodList.getSelectedIndex();
        int drinksNdx = drinksList.getSelectedIndex();
        System.out.println(removingSelection);
        if (removingSelection == 0) {
            //delete food
            String removingName = foodList.getSelectedValue().split("\\.")[0];
            for (Food i : selectedFood.keySet()) {
                System.out.println(i.getName(selectedLanguage) + "\t" + removingName);

                if (i.getName(selectedLanguage).equals(removingName)) {
                    totalOrderSelection -= selectedFood.get(i);
                    selectedFood.remove(i);
                }
            }

            DefaultListModel foodListModel = (DefaultListModel) foodList.getModel();
            foodListModel.removeElementAt(foodNdx);
            foodList.setModel(foodListModel);

        } else if (removingSelection == 1) {
            //delete drinks
            String removingName = drinksList.getSelectedValue().split("\\.")[0];
            System.out.println(removingName);
            System.out.println(selectedDrinks.size());
            for (Food i : selectedDrinks.keySet()) {
                if (i.getName(selectedLanguage).equals(removingName)) {
                    totalOrderSelection -= selectedDrinks.get(i);
                    selectedDrinks.remove(i);
                }
            }
            System.out.println("afterloop");
            DefaultListModel drinksListModel = (DefaultListModel) drinksList.getModel();
            drinksListModel.removeElementAt(drinksNdx);
            drinksList.setModel(drinksListModel);

        }
        drinksList.setSelectedIndex(-1);
        foodList.setSelectedIndex(-1);


    }//GEN-LAST:event_removeButtonMouseClicked

    private void sendOrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendOrderButtonMouseClicked

        try {
            // TODO add your handling code here:
            //client.send(new Order(this.selectedFood, this.selectedDrinks, this.thisTable.id));
            client.send(new Order(new HashMap<Food, Integer>(selectedFood), new HashMap<Food, Integer>(selectedDrinks), this.thisTable.id));
        } catch (IOException ex) {
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
        }

        for (Food i : selectedFood.keySet()) {
            db.updateCount(i, selectedFood.get(i));
        }
        for (Food i : selectedDrinks.keySet()) {
            db.updateCount(i, selectedDrinks.get(i));
        }

        this.thisTable.addOrderd(this.selectedFood, this.selectedDrinks);
        this.selectedFood.clear();
        this.selectedDrinks.clear();
        this.removingSelection = -1;

        DefaultListModel foodListModel = (DefaultListModel) foodList.getModel();
        foodListModel.removeAllElements();

        DefaultListModel drinksListModel = (DefaultListModel) drinksList.getModel();
        drinksListModel.removeAllElements();

        foodList.setModel(foodListModel);
        drinksList.setModel(drinksListModel);

        System.out.println(selectedFood.size());
        totalOrder += totalOrderSelection;
        totalOrderSelection = 0;


    }//GEN-LAST:event_sendOrderButtonMouseClicked

    private void viewBillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBillButtonMouseClicked
        // TODO add your handling code here:
        billPanel.setVisible(true);
        startPanel.setVisible(false);
        menuPanel.setVisible(false);
        cartPanel.setVisible(false);
        updateBill();
        updateInfo();

    }//GEN-LAST:event_viewBillButtonMouseClicked

    private void menuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonMouseClicked
        // TODO add your handling code here:
        billPanel.setVisible(false);
        startPanel.setVisible(false);
        cartPanel.setVisible(false);
        menuPanel.setVisible(true);
    }//GEN-LAST:event_menuButtonMouseClicked

    private void checkBillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBillButtonMouseClicked

        try {
            // TODO add your handling code here:
            client.send(new Message("check bill", this.thisTable.id));
            client.send(new SetupNewTable(this.thisTable, this.thisTable.id, "Leaving"));
        } catch (IOException ex) {
            //Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
            JFrame frame = new JFrame("Error Occured");
            JOptionPane.showMessageDialog(frame, "Lost Connection with Host", "Host Unknown", JOptionPane.ERROR_MESSAGE);
        }

        this.thisTable.reset();
        this.totalOrder = 0;
        billPanel.setVisible(false);
        startPanel.setVisible(true);
        cartPanel.setVisible(false);
        menuPanel.setVisible(false);
        setTextAccrodingToSelectedLanguage();


    }//GEN-LAST:event_checkBillButtonMouseClicked

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling code here:
        if ((int) numberOfOrderedSpinner.getValue() > 0) {
            System.out.println(foodAccordingToCetagory.get(selectedMenuIndex));
            if (foodAccordingToCetagory.get(selectedMenuIndex).getCategory(0).equals("Drinks")) {
                System.out.println("iniasndaosdasbfiu");
                selectedDrinks.put(foodAccordingToCetagory.get(selectedMenuIndex), (int) numberOfOrderedSpinner.getValue());
            } else {
                selectedFood.put(foodAccordingToCetagory.get(selectedMenuIndex), (int) numberOfOrderedSpinner.getValue());
            }
            this.totalOrderSelection += (int) numberOfOrderedSpinner.getValue();
            numberOfOrderedSpinner.setValue(1);
            setTextAccrodingToSelectedLanguage();
            this.priceLabel.setText(String.format("%.2f", foodAccordingToCetagory.get(selectedMenuIndex).getPrice()));
        }


    }//GEN-LAST:event_addButtonMouseClicked

    private void menuDisplayPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDisplayPanelMouseClicked
        // TODO add your handling code here:
        Point mouseClicked = menuDisplayPanel.getMousePosition();
        this.selectedMenuIndex = mouseClicked.x / FoodDisplayPanel.WIDTH;
        this.updateSelectedFoodIcon();
        this.priceLabel.setText(String.format("%.2f", foodAccordingToCetagory.get(selectedMenuIndex).getPrice()));

    }//GEN-LAST:event_menuDisplayPanelMouseClicked

    private void numberOfOrderedSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numberOfOrderedSpinnerStateChanged
        // TODO add your handling code here:
        this.priceLabel.setText(String.format("%.2f", foodAccordingToCetagory.get(selectedMenuIndex).getPrice() * (int) numberOfOrderedSpinner.getValue()));

    }//GEN-LAST:event_numberOfOrderedSpinnerStateChanged

    private void setUpTable(int amount) throws IOException {
        startPanel.setVisible(false);
        menuPanel.setVisible(true);
        dateObj = new Date();
        dateFormat = new SimpleDateFormat("HH:mm:ss");
        thisTable.setUp(amount, dateFormat.format(dateObj));
        topNumberLabel.setText(topNumberLabelText[selectedLanguage] + amount);
        System.out.println(thisTable.getEnteredTime());
        client.send(new SetupNewTable(thisTable, TABLE_NUMBER, "Coming In"));
        this.foodCategoryList.setSelectedIndex(0);
        String chosenCategory = foodCategoryList.getSelectedValue();
        foodAccordingToCetagory = db.getFoodByCategory(chosenCategory, selectedLanguage);
        this.addFoodToDisplay();
    }

    private void setTextAccrodingToSelectedLanguage() {
        callStaffButton.setText(callStaffButtonText[selectedLanguage]);
        welcomeLabel.setText(welcomeText[selectedLanguage]);
        numOrderedLabel.setText("" + totalOrderSelection);
        addButton.setText(addButtonText[selectedLanguage]);
        orderButton.setText(orderButtonText[selectedLanguage] + " ( " + this.totalOrderSelection + " )");
        orderedLabel.setText(orderedLabelText[selectedLanguage]);
        backButton.setText(backButtonText[selectedLanguage]);
        if (thisTable.getNumberOfPeople() != 0) {
            topNumberLabel.setText(topNumberLabelText[selectedLanguage] + thisTable.getNumberOfPeople());
        } else {
            topNumberLabel.setText("");
        }
        this.removeButton.setText(removeButtonText[selectedLanguage]);
        this.sendOrderButton.setText(sendOrderButtonText[selectedLanguage]);
        this.viewBillButton.setText(viewBillButtonText[selectedLanguage]);
        this.menuButton.setText(menuButtonText[selectedLanguage]);
        this.checkBillButton.setText(checkBillButtonText[selectedLanguage]);
        this.infoTotalMenu.setText(infoTotalMenuText[selectedLanguage]);
        this.infoTotalPrice.setText(infoTotalPriceText[selectedLanguage]);
        this.infoPriceEach.setText(infoPriceEachText[selectedLanguage]);
        if (this.cartPanel.isVisible()) {
            updateSelectedMenu();
        }
        if (this.billPanel.isVisible()) {
            this.updateBill();
            this.updateInfo();
        }
        this.updateCategoryList();
        this.addFoodToDisplay();

    }

    private void buttonConfig() {
        addButton.setIconTextGap(15);
        addButton.setHorizontalTextPosition(SwingConstants.LEFT);
        callStaffButton.setIconTextGap(15);
        orderedLabel.setIconTextGap(35);
        backButton.setIconTextGap(15);
        removeButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        removeButton.setHorizontalTextPosition(SwingConstants.CENTER);
        sendOrderButton.setIconTextGap(12);
        sendOrderButton.setHorizontalTextPosition(SwingConstants.LEFT);
        checkBillButton.setHorizontalTextPosition(SwingConstants.LEFT);
        viewBillButton.setIconTextGap(12);
        viewBillButton.setHorizontalTextPosition(SwingConstants.LEFT);

    }

    private void updateSelectedMenu() {
        System.out.println("select");

        DefaultListModel foodListModel = (DefaultListModel) foodList.getModel();
        foodListModel.removeAllElements();

        DefaultListModel drinksListModel = (DefaultListModel) drinksList.getModel();
        drinksListModel.removeAllElements();

        for (Food i : selectedFood.keySet()) {
            String s = String.format("%-50s %-14d ฿%8.2f", i.getName(selectedLanguage) + ".", selectedFood.get(i), i.getPrice() * selectedFood.get(i));
            foodListModel.addElement(s);
        }

        for (Food i : selectedDrinks.keySet()) {
            String s = String.format("%-50s %-14d ฿%8.2f", i.getName(selectedLanguage) + ".", selectedDrinks.get(i), i.getPrice() * selectedDrinks.get(i));
            drinksListModel.addElement(s);
        }

        foodList.setModel(foodListModel);
        drinksList.setModel(drinksListModel);
        System.out.println("selected");
    }

    private void updateBill() {

        this.billTableNumberLabel.setText("" + this.thisTable.id);
        this.billNumberOfPeopleLabel.setText("" + this.thisTable.numberOfPeople);
        this.billTimeLabel.setText("" + this.thisTable.getEnteredTime());

        this.billFoodQtyLabel.setText("<html>");
        this.billFoodDescriptionLabel.setText("<html>");
        this.billFoodPriceLabel.setText("<html>");
        for (Food i : this.thisTable.foodOrdered.keySet()) {
            this.billFoodQtyLabel.setText(this.billFoodQtyLabel.getText() + "<br>" + this.thisTable.foodOrdered.get(i)); //******************************************//
            this.billFoodDescriptionLabel.setText(this.billFoodDescriptionLabel.getText() + "<br>" + i.getName(selectedLanguage));
            this.billFoodPriceLabel.setText(this.billFoodPriceLabel.getText() + "<br>" + String.format("฿ %10.2f", i.getPrice() * this.thisTable.foodOrdered.get(i)));
        }
        this.billFoodQtyLabel.setText(this.billFoodQtyLabel.getText() + "</html>");
        this.billFoodDescriptionLabel.setText(this.billFoodDescriptionLabel.getText() + "</html>");
        this.billFoodPriceLabel.setText(this.billFoodPriceLabel.getText() + "</html>");

        //Drinks Section
        this.billDrinksQtyLabel.setText("<html>");
        this.billDrinksDescriptionLabel.setText("<html>");
        this.billDrinksPriceLabel.setText("<html>");

        for (Food i : this.thisTable.drinksOrdered.keySet()) {
            this.billDrinksQtyLabel.setText(this.billDrinksQtyLabel.getText() + "<br>" + this.thisTable.drinksOrdered.get(i)); //******************************************//
            billDrinksDescriptionLabel.setText(billDrinksDescriptionLabel.getText() + "<br>" + i.getName(selectedLanguage));
            billDrinksPriceLabel.setText(billDrinksPriceLabel.getText() + "<br>" + String.format("฿ %10.2f", i.getPrice() * this.thisTable.drinksOrdered.get(i)));
        }
        this.billDrinksQtyLabel.setText(this.billDrinksQtyLabel.getText() + "</html>");
        billDrinksDescriptionLabel.setText(billDrinksDescriptionLabel.getText() + "</html>");
        billDrinksPriceLabel.setText(billDrinksPriceLabel.getText() + "</html>");

        //Money Section
        vatCostLabel.setText(String.format("฿ %8.2f", this.thisTable.getVAT()));
        serviceChargeCostLabel.setText(String.format("฿ %8.2f", this.thisTable.getServiceCharge()));
        totalCostLabel.setText(String.format("฿ %8.2f", this.thisTable.getTotalPrice()));
    }

    public void updateInfo() {
        this.infoTotalMenuNumber.setText("" + this.totalOrder);
        this.infoTotalPriceNumber.setText("฿ " + String.format("%.2f", this.thisTable.getTotalPrice()));
        this.infoPriceEachNumber.setText("฿ " + String.format("%.2f", this.thisTable.getTotalPrice() / this.thisTable.getNumberOfPeople()));
    }

    public void updateCategoryList() {
        DefaultListModel categoryListModel = (DefaultListModel) foodCategoryList.getModel();
        categoryListModel.removeAllElements();

        if (selectedLanguage == 0) {
            for (String i : this.foodCategoryEnglish) {
                categoryListModel.addElement(i);
            }
        } else {
            for (String i : this.foodCategoryThai) {
                categoryListModel.addElement(i);
            }
        }
        foodCategoryList.setModel(categoryListModel);
    }

    public void addFoodToDisplay() {
        try {
            menuDisplayPanel.removeAll();
            foodAccordingToCetagoryIcon.clear();
            int count = 0;
            for (Food i : this.foodAccordingToCetagory) {
                foodAccordingToCetagoryIcon.add(new FoodDisplayPanel(i, selectedLanguage));
                menuDisplayPanel.add(foodAccordingToCetagoryIcon.get(count++));
            }
            menuDisplayPanel.revalidate();
            menuDisplayPanel.repaint();
            updateSelectedFoodIcon();
        } catch (Exception e) {

        }
    }

    public void updateSelectedFoodIcon() {
        int count = 0;
        for (FoodDisplayPanel i : foodAccordingToCetagoryIcon) {
            i.setBorder(selectedMenuIndex == count++);
        }
        numberOfOrderedSpinner.setValue(1);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 
        try {
            Object[] setUpTable = {"1", "2", "3", "4", "5", "6",
                "7", "8", "9", "10", "11", "12"};
            JFrame frame = new JFrame("Error Occured");

            String temp = (String) JOptionPane.showInputDialog(frame,
                    "Which Table is this? ", "Setting up table's number",
                    JOptionPane.QUESTION_MESSAGE, null, setUpTable, setUpTable[0]);

            TABLE_NUMBER = Integer.parseInt(temp);
        } catch (Exception e) {
            TABLE_NUMBER = 1;
        }
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TableGui t = new TableGui();
                t.setVisible(true);
                t.setupConnectionWithHost();

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bahtLabel;
    private javax.swing.JLabel billBarLabel;
    private javax.swing.JLabel billBarLabel2;
    private javax.swing.JLabel billDescriptionLabel;
    private javax.swing.JLabel billDiscountCostLabel;
    private javax.swing.JLabel billDiscountLabel;
    private javax.swing.JLabel billDrinksDescriptionLabel;
    private javax.swing.JLabel billDrinksPriceLabel;
    private javax.swing.JLabel billDrinksQtyLabel;
    private javax.swing.JLabel billFoodDescriptionLabel;
    private javax.swing.JLabel billFoodPriceLabel;
    private javax.swing.JLabel billFoodQtyLabel;
    private javax.swing.JPanel billInfoPanel;
    private javax.swing.JLabel billNumberOfPeopleLabel;
    private javax.swing.JPanel billPanel;
    private javax.swing.JLabel billPeopleLabel;
    private javax.swing.JLabel billPriceLabel;
    private javax.swing.JLabel billQtyLabel;
    private javax.swing.JLabel billTableLabel;
    private javax.swing.JLabel billTableNumberLabel;
    private javax.swing.JLabel billTimeLabel;
    private javax.swing.JButton callStaffButton;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JButton checkBillButton;
    private javax.swing.JList<String> drinksList;
    private javax.swing.JPanel extraCostLabel;
    private javax.swing.JList<String> foodCategoryList;
    private javax.swing.JList<String> foodList;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel infoPriceEach;
    private javax.swing.JLabel infoPriceEachNumber;
    private javax.swing.JLabel infoTotalMenu;
    private javax.swing.JLabel infoTotalMenuNumber;
    private javax.swing.JLabel infoTotalPrice;
    private javax.swing.JLabel infoTotalPriceNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton menuButton;
    private javax.swing.JPanel menuDisplayPanel;
    private javax.swing.JScrollPane menuDisplayScrollPane;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel numOrderedLabel;
    private javax.swing.JSpinner numberOfOrderedSpinner;
    private javax.swing.JButton orderButton;
    private javax.swing.JLabel orderdLabel;
    private javax.swing.JLabel orderedLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton removeButton;
    private javax.swing.JScrollPane selectedDisplayScrollPane;
    private javax.swing.JPanel selectedPanel;
    private javax.swing.JButton sendOrderButton;
    private javax.swing.JLabel sericeChargeLabel;
    private javax.swing.JLabel serviceChargeCostLabel;
    private javax.swing.JButton startButton1;
    private javax.swing.JButton startButton2;
    private javax.swing.JButton startButton3;
    private javax.swing.JButton startButton4;
    private javax.swing.JButton startButton5;
    private javax.swing.JButton startButton6;
    private javax.swing.JButton startButton7;
    private javax.swing.JButton startButton8;
    private javax.swing.JPanel startButtonLabel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel toEnglish;
    private javax.swing.JLabel toThai;
    private javax.swing.JLabel topNumberLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JLabel vatCostLabel;
    private javax.swing.JLabel vatLabel;
    private javax.swing.JButton viewBillButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
